global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'product-service'
    metrics_path: '/actuator/product/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'Product Service'
  - job_name: 'order-service'
    metrics_path: '/actuator/order/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'Order Service'
  - job_name: 'inventory-service'
    metrics_path: '/actuator/inventory/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'Inventory Service'